version: '3.1'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8000:80'
      - '443'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - app
    env_file: ./.env

  app:
    image: node:latest
    container_name: my-app
    working_dir: /application
    volumes:
      - .:/application
    links:
      - mysql
    ports:
      - '9000'
    entrypoint: /application/start_application.sh
    env_file: ./.env
    environment:
      'NODE_ENV': 'development'

  mysql:
    env_file: ./.env
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      'MYSQL_DATABASE': 'master'
      'MYSQL_ROOT_PASSWORD': '1234'
